### ISSUE TITLE
[GraphStudio-Backend] Proposal: overall architecture and tasks list

### ISSUE THREAD

**Issue by robocanic** [alibaba/spring-ai-alibaba#180]
# Backstory
**GraphStudio** aims to provide low-code functions for Java developers to **start/build** their AI-Native Apps using Java and spring-ai-alibaba.

We are currently planning 4 features for the GraphStudio
1. Support different app types like chatbot, workflow.
2. Build workflows/chatbots in low-code functions and make them can be exported/imported in DSL.
3. Run workflows/chatbots after completing the construction of the app.
4. **_Generate Java code based on the specific type of node in a workflow, and generate project starters based on the structure of workflow/chatbot built in frontend._** 

# Overall architecture
To achieve the goals we mentioned above, I've drawn a overall architecture for backend: 
![image](https://github.com/user-attachments/assets/2cddf935-6225-43e0-9def-6229a7385224)

# Task List
- App model design 
  - [x] Workflow
  - [ ] ChatBot 
- DSL export/import
  - [ ] Workflow: support a series LLM, Code, DocsRetriever etc. (Some of them have already been completed)
  - [ ] Chatbot
- App crud
  - [x] CRUD api 
  - [x] App persistence abstraction
  - [ ] App persistence implementation (Already have a simple memory implementation)
- Generator
  - [ ] #960
  - [ ] ChatBotGenerator: generate a starter project based on the ChatBot Model
  - [ ] NodeGenerator: generate a code template based on the Node Model
- Runner
  - [ ] WorkflowRunner: run a workflow based on a Workflow Model
  - [ ] ChatBotRunner: run a chatbot based on a ChatBot Model
  - [ ] NodeRunner: run a single node in a workflow based on a NodeData Model
